### PR TITLE
Shared messages improvements proposal

### PR DESCRIPTION
**Pull request by oskin1**
1. ChangedState(r: StateReader, progressInfoOpt: Option[ProgressInfo[PMOD]]) improved `progressInfoOption` added.
2. ChangedStateFailed(r: StateReader, progressInfoOpt: Option[ProgressInfo[PMOD]]) introduced.
3. RollbackFailed removed.

### CODE REVIEW

**Comment by kushti** [comment]
@oskin1 are tests failing now?

**Comment by oskin1** [comment]
@kushti All tests are passing on my local machine

**Comment by kushti** [comment]
@oskin1 ChangedStateFailed hides a reason of a failure.  SemanticallyFailedModification and RollbackFailed show what happened pretty well. Let's add RolbackSuccessful if you want to get this info, and done with that single class

**Comment by kushti** [comment]
@oskin1 Based on my previous comment, I'm rejecting the PR

**Pull request closed without merging**
